name: Reset Daily Search Count

on:
  schedule:
    # 毎日UTC 15:00 (日本時間 0:00) に実行
    - cron: "0 15 * * *"
  # 手動実行用
  workflow_dispatch:

jobs:
  reset-count:
    runs-on: ubuntu-latest
    steps:
      - name: Call Reset Function
        run: |
          echo "Attempting to reset daily search count..."
          
          # 認証なしでシンプルに実行
          response=$(curl -s -X POST "https://pmjdyztlqovnqjwavbpb.functions.supabase.co/reset-daily-search-count" \
            -H "Content-Type: application/json" \
            -d '{}')
          
          echo "Response: $response"
          
          # レスポンスから成功かどうかを判断
          if echo "$response" | grep -q "success.*true"; then
            echo "✅ Successfully reset daily search count"
            exit 0
          else
            echo "❌ Failed to reset daily search count: $response"
            exit 1
          fi
