name: Reset Daily Search Count

on:
  schedule:
    # 毎日UTC 15:00 (日本時間 0:00) に実行
    - cron: "0 15 * * *"
  # 手動実行用
  workflow_dispatch:

jobs:
  reset-count:
    runs-on: ubuntu-latest
    steps:
      - name: Call Database Function Directly
        run: |
          echo "Attempting to reset daily search count via REST API..."
          
          # Supabase REST API を直接呼び出す
          response=$(curl -s -X POST "https://pmjdyztlqovnqjwavbpb.supabase.co/rest/v1/rpc/reset_daily_search_count" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json")
          
          echo "Response: $response"
          
          # レスポンスにエラーがないか確認
          if [[ "$response" == +([0-9]) ]] || echo "$response" | grep -q -v "error"; then
            echo "✅ Successfully reset daily search count. Count: $response"
            exit 0
          else
            echo "❌ Failed to reset daily search count: $response"
            exit 1
          fi
